sudo yum install emacs
sudo yum install git
sudo yum install gmp-devel
sudo yum install mpfr-devel
sudo yum install libmpc-devel
sudo apt-get install libx11-dev
sudo yum install libX11-devel
sudo yum install libXpm-devel
sudo yum install libXft-devel
sudo yum install libXext-devel